export const BEGIN_FETCH_USERS = "BEGIN_FETCH_USERS"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR"

export const BEGIN_CREATE_USER = "BEGIN_CREATE_USER"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR = "CREATE_USER_ERROR"

export const CREATE_USER_PAGE_CLEAN_UP = "CREATE_USER_PAGE_CLEAN_UP";

